application: app
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration: 10d

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  mime_type: text/plain
  expiration: 10d

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

# Static file mappings
- url: /css
  mime_type: text/css
  expiration: 10000d
  static_dir: static/css
- url: /blueprint
  mime_type: text/css
  expiration: 10000d
  static_dir: static/blueprint  
- url: /img
  static_dir: static/img
  expiration: 10000d
- url: /js
  static_dir: static/js
  expiration: 10000d
- url: /app
  static_dir: static/app

# Catch-all for static files
- url: /static
  static_dir: static
  expiration: 10000d

- url: .*
  script: main.py

error_handlers:
- file: sketch/templates/server_error.html
- error_code: over_quota
  file: sketch/templates/server_error.html
- error_code: dos_api_denial
  file: sketch/templates/server_error.html
- error_code: timeout
  file: sketch/templates/server_error.html

builtins:
- datastore_admin: on
- appstats: on
- admin_redirect: on
- remote_api: on

inbound_services:
- warmup

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/git/.*
- ^(.*/)?.*/svn/.*
- ^(.*/)?\..*
- ^(.*/)?README$
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*\.txt$
- ^(.*/)?.*\.md$